---
title: "02-annotating-sunflower-genes"
author: "Hannah Nowers"
date: "2026-01-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash, Setupn and Query Sequence}

cd ../data
pwd

curl -O https://gannet.fish.washington.edu/seashell/bu-github/paper-pycno-sswd-2021-2022/data/augustus.hints.codingseq #downloading query seq

mv augustus.hints.codingseq pycnopodia.helianthoides.genes.fa # renaming data file

head -n 5 pycnopodia.helianthoides.genes.fa #Looking at the start of my query sequence

echo "How many sequences are there?" #echo prints the follow line into terminal, this labels the ouput so you know what the number refers to

grep -c ">" ../data/pycnopodia.helianthoides.genes.fa # grep-> searches for patterns in a file, -c -> counts the number of lines that match, ">" looks for the > characters(FASTA headings), Ab_4denovo_CLC6_a.fa is telling it which files to search. Overall, looking for the number of lines that start with > which tells it the number of sequences
```


```{bash, Running Blast}

#Now I need to run my query seq(pycnopodia.helianthoides.genes) through the blast db
#bin -> is the folder that contains the blast executables

~/GitHub/Github-Practice/Data/ncbi-blast-2.17.0+/bin/blastx \
-query ../../seastar-capstone/data/pycnopodia.helianthoides.genes.fa \
-db ../../Github-Practice/blastdb/uniprot_sprot_r2023_01 \
-out ../../Seastar-capstone/output/pycnopodia_gene_blastx.tab \
-evalue 1E-20 \
-num_threads 20 \
-max_target_seqs 1 \
-outfmt 6 #line 1: tells it what version of Blast, what bin, and what executable I want to use, blastx tales the DNA/RNA sequences translates them into proteins and searches the protein database, second line: -query specifies the sequence I want to search the trailing bit just tell it where the file is, third line: tell it what database to search against trailing bit tell is where the database is, fourth line: tells blast where to save the results, fifth line: -evalue -> sets the expectation value cutoff, means BLAST with only report hit thats have a 1E-20 probability of occuring, sixth line: -num_threads -> tells the computer how many CPU threads to use, run 20 threads in parallel which speeds up searching, seventh line: -max_target_seqs: limits how many top hits BLAST reports for each query, 1 -> only the best hit per query sequence will be saved, eighth line: -outfmt sets the ouput format, 6= table format

head -2 ../output/pycnopodia_gene_blastx.tab
wc -l ../output/pycnopodia_gene_blastx.tab
```

```{bash, Checking Data}
head -2 ../output/pycnopodia_gene_blastx.tab
wc -l ../output/pycnopodia_gene_blastx.tab

curl -O -H "Accept: text/plain; format=tsv" "https://rest.uniprot.org/uniprotkb/stream?compressed=true&fields=accession%2Creviewed%2Cid%2Cprotein_name%2Cgene_names%2Corganism_name%2Clength%2Cgo&format=tsv&query=%28*%29+AND+%28reviewed%3Atrue%29" #link with additional gene information, -H returns the correct file format

pwd

mv "stream" ../data/uniprot_table_r2023_01.tab ../data/uniprot_table_r2023_01.tab.gz #renaming and moving for later use

gunzip ../data/uniprot_table_r2023_01.tab.gz #unzipping file

```
```{bash, Joining blast table with annotation table}

head -2 ../output/pycnopodia_gene_blastx.tab # checking the first two lines of my blast table
wc -l ../output/pycnopodia_gene_blastx.tab # wc-> word count, -1 <- count one line
```
```{bash, joining tables continued}

sed 's/|/\t/g' ../output/pycnopodia_gene_blastx.tab \
> ../output/pycnopodia-uniprot_blastx_sep.tab #first line: sed 's/|/\t/g'-> mean translate and replace every \ with a tab, Second line: > means put Ab_4-uniprot_blastx.tab through the translation, replacing | with tab and then making a new file Ab_4-uniprot_blastx_sep.tab

pwd

head -2 ../data/uniprot_table_r2023_01.tab # Checking what it looks like
wc -l ../data/uniprot_table_r2023_01.tab # checking the word count on the first line


```

```{r, installing packages and making table}
install.packages("tidyverse")
install.packages("kableExtra")

library(tidyverse)
library(kableExtra)

bltabl <- read.csv("../output/pycnopodia-uniprot_blastx_sep.tab", sep = '\t', header = FALSE) #blast table
spgo <- read.csv("../data/uniprot_table_r2023_01.tab", sep = '\t', header = TRUE) # annotation table
str(spgo)

names(spgo) # Seeing exactly what R has named the columns

kbl(
head(
  left_join(bltabl, spgo,  by = c("V3" = "Entry")) %>%
  select(V1, V3, V13, Protein.names, Organism, Gene.Ontology..GO.) %>% mutate(V1 = str_replace_all(V1, 
            pattern = "solid0078_20110412_FRAG_BC_WHITE_WHITE_F3_QV_SE_trimmed", replacement = "Ab"))
)
) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))



```